// @ts-nocheck
/* GENERATED by scripts/build-rhio-engine.mjs from lib/rhio3d/src — edit the sources, then rebuild. */
/** Installs presets, wardrobe options, motion groups and powers on G.RHIO. Safe on the server (no three.js). */
export function installData(G) {
/* RHIO — roster, wardrobe options, motions & skills metadata. */
(function (G) {
'use strict';
const R = G.RHIO;
const h = (o) => o; // readability
// skin tones (light → deep)
const SK = ['#f3d2b8', '#e8b894', '#d49a72', '#b97a52', '#8e5a3b', '#6a4029', '#4a2b1d'];
const HAIR = ['#1b1512', '#3a2a22', '#6b4a33', '#a5733f', '#d9b27a', '#e8e2d6', '#c8ff24', '#ff7eb6', '#7aa7ff', '#b28dff'];

R.WARDROBE = {
  build: [['slim', 'Slim'], ['regular', 'Regular'], ['curvy', 'Curvy'], ['broad', 'Broad']],
  hair: [['short', 'Short'], ['swept', 'Swept'], ['buzz', 'Buzz'], ['spiky', 'Spiky'], ['curly', 'Curly'], ['afro', 'Afro'], ['bob', 'Bob'], ['long', 'Long'], ['ponytail', 'Ponytail'], ['twintails', 'Twin tails'], ['bun', 'Bun'], ['mohawk', 'Mohawk'], ['none', 'None']],
  facial: [['none', 'None'], ['stubble', 'Stubble'], ['beard', 'Beard']],
  top: [['tee', 'T-shirt'], ['tank', 'Tank top'], ['sweater', 'Sweater'], ['hoodie', 'Hoodie'], ['tracksuit', 'Track jacket'], ['bomber', 'Flight jacket'], ['jacket', 'Open jacket'], ['suit', 'Suit'], ['coat', 'Long coat'], ['robe', 'Robe'], ['armor', 'Armor'], ['spacesuit', 'Spacesuit']],
  bottom: [['pants', 'Pants'], ['joggers', 'Joggers'], ['cargo', 'Cargo'], ['shorts', 'Shorts'], ['skirt', 'Skirt']],
  legwear: [['bare', 'Bare legs'], ['tights', 'Tights']],
  shoes: [['sneaker', 'Sneakers'], ['boot', 'Boots'], ['loafer', 'Loafers']],
  head: [['none', 'None'], ['cap', 'Cap'], ['beanie', 'Beanie'], ['hat', 'Explorer hat'], ['headphones', 'Headphones'], ['halo', 'Halo'], ['ears', 'Cat ears'], ['helmet', 'Space helmet']],
  face: [['none', 'None'], ['glasses', 'Glasses'], ['shades', 'Shades'], ['visor', 'Visor']],
  back: [['none', 'None'], ['backpack', 'Backpack'], ['jetpack', 'Jetpack'], ['cape', 'Cape'], ['scarf', 'Scarf']],
  finish: [['matte', 'Matte'], ['gloss', 'Gloss']],
  swatches: ['#c8ff24', '#1f2528', '#2b3a33', '#f1efe6', '#9b73dd', '#4fb6ca', '#ec89b7', '#e0664f', '#f2b84b', '#466dcc', '#356f69', '#a58f55', '#7487a8', '#6b3fa0'],
  skin: SK, hairColors: HAIR,
  eyes: ['#4a3526', '#2d5d8a', '#3f7a4a', '#7a5a2a', '#5a5a66', '#8a3fa0'],
  glow: ['#c8ff24', '#5ee0ff', '#ff6fb1', '#ffd25e', '#b28dff', '#ff8a4c'],
};

const P = [];
const hu = (id, name, role, desc, sig, look) => P.push({ id, name, role, desc, sig, cat: 'Humanoid', look: Object.assign({ kind: 'human' }, look) });
const co = (id, name, role, desc, sig, look) => P.push({ id, name, role, desc, sig, cat: 'Companion', look: Object.assign({ kind: 'companion', model: id }, look) });

// original 9 humanoids, kept by id so saved agents still open
hu('atlas', 'Atlas', 'OPERATOR', 'Sharp suit, calm voice, zero wasted words.', 'scan', { build: 'regular', skin: SK[2], hair: { style: 'swept', color: HAIR[1] }, facial: 'stubble', top: { type: 'suit', color: '#1f2428', accent: '#c8ff24' }, bottom: { type: 'pants', color: '#1a1e21' }, shoes: { type: 'loafer', color: '#141414' }, face: 'visor', eyes: '#3a2a20' });
hu('nova', 'Nova', 'CREATIVE', 'Flight jacket, notebook full of wild ideas.', 'hype', { build: 'slim', skin: SK[1], hair: { style: 'bob', color: '#2a1c1a' }, top: { type: 'bomber', color: '#9b73dd', accent: '#c8ff24' }, bottom: { type: 'joggers', color: '#2b2440' }, shoes: { type: 'sneaker', color: '#f1efe6' }, eyes: '#5a3a2a' });
hu('orbit', 'Orbit', 'EXPLORER', 'Suited up for questions beyond the map.', 'levitate', { build: 'regular', skin: SK[3], hair: { style: 'short', color: HAIR[0] }, top: { type: 'spacesuit', color: '#e3e8e4', accent: '#c8ff24' }, bottom: { type: 'pants', color: '#e3e8e4' }, head: 'helmet', back: 'none', eyes: '#3a2a20' });
hu('kira', 'Kira', 'STRATEGIST', 'Long coat, longer view of the board.', 'shield', { build: 'slim', skin: SK[0], hair: { style: 'long', color: '#1e1714' }, top: { type: 'coat', color: '#356f69', accent: '#e9d9a8' }, bottom: { type: 'pants', color: '#1b2624' }, shoes: { type: 'boot', color: '#1d1a18' }, eyes: '#2d5d8a' });
hu('dash', 'Dash', 'RUNNER', 'Always three steps ahead of the task.', 'blink', { build: 'regular', skin: SK[4], hair: { style: 'buzz', color: HAIR[0] }, top: { type: 'tracksuit', color: '#466dcc', accent: '#f1efe6' }, bottom: { type: 'joggers', color: '#466dcc' }, shoes: { type: 'sneaker', color: '#c8ff24' }, eyes: '#3a2a20' });
hu('byte', 'Byte', 'ANDROID', 'A humanoid shell with a very curious core.', 'orb', { build: 'regular', headStyle: 'screen', skin: '#c8ff24', hair: { style: 'none', color: '#222222' }, top: { type: 'tank', color: '#c8ff24', accent: '#2a302c' }, bottom: { type: 'pants', color: '#3a4540' }, shoes: { type: 'boot', color: '#2a302c' }, finish: 'gloss', glow: '#5ee0ff' });
hu('echo', 'Echo', 'CREATOR', 'Headphones on, ideas in rhythm.', 'hype', { build: 'curvy', skin: SK[2], hair: { style: 'ponytail', color: '#3b1f2a' }, top: { type: 'hoodie', color: '#d2759b', accent: '#f1efe6' }, bottom: { type: 'joggers', color: '#2a2226' }, shoes: { type: 'sneaker', color: '#f1efe6' }, head: 'headphones', accColor: '#1f2327', eyes: '#4a3526', glow: '#ff6fb1' });
hu('terra', 'Terra', 'RESEARCHER', 'Field notes, dusty boots, good sources.', 'scan', { build: 'regular', skin: SK[3], hair: { style: 'short', color: HAIR[2] }, facial: 'beard', top: { type: 'jacket', color: '#a58f55', accent: '#6b4a33' }, bottom: { type: 'cargo', color: '#5d5236' }, shoes: { type: 'boot', color: '#4a3526' }, head: 'hat', back: 'backpack', accColor: '#6b4a33', eyes: '#3f7a4a', glow: '#ffd25e' });
hu('volt', 'Volt', 'SENTINEL', 'Heavy armor, light on its feet.', 'shield', { build: 'broad', skin: SK[5], hair: { style: 'mohawk', color: '#c8ff24' }, top: { type: 'armor', color: '#2c343c', accent: '#7487a8' }, bottom: { type: 'cargo', color: '#2c343c' }, shoes: { type: 'boot', color: '#1d2126' }, eyes: '#4a3526' });
// new humanoids
hu('vesper', 'Vesper', 'DESIGNER', 'Sees the grid behind every idea.', 'hype', { build: 'curvy', skin: SK[5], hair: { style: 'afro', color: '#1b1512' }, top: { type: 'tee', color: '#f2b84b', accent: '#1f2528' }, bottom: { type: 'skirt', color: '#1f2528' }, legwear: 'tights', shoes: { type: 'sneaker', color: '#f1efe6' }, face: 'glasses', accColor: '#e0664f', eyes: '#4a3526', glow: '#ffd25e' });
hu('rook', 'Rook', 'BUILDER', 'Ships first drafts before lunch.', 'orb', { build: 'regular', skin: SK[3], hair: { style: 'spiky', color: '#1b1512' }, top: { type: 'hoodie', color: '#2b3a33', accent: '#c8ff24' }, bottom: { type: 'joggers', color: '#1f2528' }, shoes: { type: 'sneaker', color: '#e0664f' }, head: 'cap', accColor: '#c8ff24', eyes: '#3a2a20' });
hu('mira', 'Mira', 'ANALYST', 'Turns messy numbers into clear answers.', 'scan', { build: 'slim', skin: SK[1], hair: { style: 'twintails', color: '#7aa7ff' }, top: { type: 'sweater', color: '#f1efe6', accent: '#7aa7ff' }, bottom: { type: 'skirt', color: '#466dcc' }, legwear: 'bare', shoes: { type: 'loafer', color: '#2a1f1a' }, eyes: '#2d5d8a', glow: '#5ee0ff' });
hu('juno', 'Juno', 'FOUNDER', 'Pitch-ready, deck in one hand.', 'shield', { build: 'curvy', skin: SK[4], hair: { style: 'bun', color: '#2a1c1a' }, top: { type: 'suit', color: '#e3ddd0', accent: '#e0664f' }, bottom: { type: 'pants', color: '#e3ddd0' }, shoes: { type: 'loafer', color: '#e0664f' }, face: 'shades', eyes: '#4a3526', glow: '#ff8a4c' });
hu('cole', 'Cole', 'TRADER', 'Watches the tape, keeps the calm.', 'blink', { build: 'broad', skin: SK[2], hair: { style: 'short', color: '#1b1512' }, facial: 'stubble', top: { type: 'tank', color: '#1f2528', accent: '#c8ff24' }, bottom: { type: 'shorts', color: '#356f69' }, shoes: { type: 'sneaker', color: '#1f2528' }, back: 'scarf', accColor: '#c8ff24', eyes: '#3a2a20' });
hu('lumi', 'Lumi', 'ORACLE', 'Quiet, bright, always one question deeper.', 'levitate', { build: 'slim', skin: SK[0], hair: { style: 'long', color: '#e8e2d6' }, top: { type: 'robe', color: '#f1efe6', accent: '#b28dff' }, bottom: { type: 'pants', color: '#f1efe6' }, shoes: { type: 'loafer', color: '#b28dff' }, head: 'halo', eyes: '#8a3fa0', glow: '#b28dff' });
hu('otto', 'Otto', 'GUIDE', 'Big laugh, bigger backpack of know-how.', 'shield', { build: 'broad', skin: SK[4], hair: { style: 'curly', color: '#1b1512' }, facial: 'beard', top: { type: 'jacket', color: '#e0664f', accent: '#1f2528' }, bottom: { type: 'cargo', color: '#3a4540' }, shoes: { type: 'boot', color: '#3a2a22' }, back: 'backpack', accColor: '#2b3a33', eyes: '#4a3526', glow: '#ff8a4c' });
hu('wren', 'Wren', 'STORYTELLER', 'Every summary reads like a good story.', 'hype', { build: 'slim', skin: SK[2], hair: { style: 'long', color: '#3a2a22' }, top: { type: 'bomber', color: '#ec89b7', accent: '#f1efe6' }, bottom: { type: 'skirt', color: '#2b2440' }, legwear: 'tights', shoes: { type: 'boot', color: '#1f2528' }, head: 'ears', eyes: '#4a3526', glow: '#ff6fb1' });
hu('zara', 'Zara', 'DEFENDER', 'Checks every claim twice.', 'shield', { build: 'regular', skin: SK[6], hair: { style: 'bob', color: '#ff7eb6' }, top: { type: 'armor', color: '#f1efe6', accent: '#ec89b7' }, bottom: { type: 'pants', color: '#2b2440' }, shoes: { type: 'boot', color: '#f1efe6' }, eyes: '#4a3526', glow: '#ff6fb1' });
hu('felix', 'Felix', 'TINKERER', 'Takes the problem apart, rebuilds it better.', 'orb', { build: 'regular', skin: SK[1], hair: { style: 'curly', color: '#a5733f' }, top: { type: 'tee', color: '#4fb6ca', accent: '#f1efe6' }, bottom: { type: 'cargo', color: '#a58f55' }, shoes: { type: 'sneaker', color: '#f2b84b' }, face: 'glasses', back: 'jetpack', accColor: '#1f2528', eyes: '#3f7a4a', glow: '#5ee0ff' });
hu('ines', 'Ines', 'SCHOLAR', 'Reads the footnotes so you do not have to.', 'scan', { build: 'regular', skin: SK[1], hair: { style: 'bun', color: '#6b4a33' }, top: { type: 'coat', color: '#6b3fa0', accent: '#f2b84b' }, bottom: { type: 'pants', color: '#2b2440' }, shoes: { type: 'boot', color: '#2a1f1a' }, face: 'glasses', accColor: '#f2b84b', eyes: '#7a5a2a', glow: '#b28dff' });
hu('taro', 'Taro', 'CURATOR', 'Finds the three links that matter.', 'blink', { build: 'slim', skin: SK[1], hair: { style: 'short', color: '#1b1512' }, top: { type: 'jacket', color: '#1f2528', accent: '#c8ff24' }, bottom: { type: 'shorts', color: '#2b3a33' }, shoes: { type: 'sneaker', color: '#f1efe6' }, head: 'beanie', back: 'cape', accColor: '#c8ff24', eyes: '#3a2a20' });
hu('noor', 'Noor', 'NAVIGATOR', 'Maps the route from question to answer.', 'levitate', { build: 'curvy', skin: SK[3], hair: { style: 'ponytail', color: '#1b1512' }, top: { type: 'spacesuit', color: '#f1efe6', accent: '#ff8a4c' }, bottom: { type: 'pants', color: '#f1efe6' }, back: 'jetpack', eyes: '#4a3526', glow: '#ff8a4c' });
// companions (original ids kept)
co('scout', 'Scout', 'RESEARCH BOT', 'An orbit of curiosity.', 'scan', { top: { type: 'tee', color: '#f1efe6', accent: '#c8ff24' }, glow: '#c8ff24' });
co('maker', 'Maker', 'WORKSHOP BOT', 'A pocket-sized workshop.', 'orb', { top: { type: 'tee', color: '#b7a1ef', accent: '#c8ff24' }, glow: '#c8ff24' });
co('guardian', 'Guardian', 'SHIELD BOT', 'A steady shield for your work.', 'shield', { top: { type: 'tee', color: '#e3ebe8', accent: '#7487a8' }, glow: '#c8ff24' });

R.PRESETS = P;
R.getPreset = id => P.find(p => p.id === id) || P[0];

/* motions shown in the deck */
R.MOTION_GROUPS = [
  ['Gestures', ['Wave', 'Nod', 'Shrug', 'Point', 'Clap', 'Salute', 'Bow']],
  ['Moods', ['Idle', 'Think', 'Typing', 'Laugh', 'Cheer', 'Stretch', 'Victory']],
  ['Moves', ['Walk', 'Run', 'Jump', 'Spin', 'Dance', 'Disco']],
];

/* power skills (character actions) */
R.POWERS = [
  { id: 'orb', name: 'Pulse Orb', key: '1', cd: 4, desc: 'Charges an energy orb between the hands and launches it.' },
  { id: 'shield', name: 'Aegis', key: '2', cd: 6, desc: 'Raises a hex shield dome around the agent.' },
  { id: 'blink', name: 'Blink', key: '3', cd: 5, desc: 'Dissolves and re-forms a step to the side.' },
  { id: 'levitate', name: 'Levitate', key: '4', cd: 7, desc: 'Floats above the pad with a ring of light.' },
  { id: 'scan', name: 'Deep Scan', key: '5', cd: 5, desc: 'Sweeps a scanner ring and reads the agent profile.' },
  { id: 'hype', name: 'Hype', key: '6', cd: 3, desc: 'Confetti burst and a cheer.' },
];
})(G);
}
export const RHIO_DATA = (() => { const G = { RHIO: {} }; installData(G); return G.RHIO; })();
