import type {Agent} from './agents';
export function sampleResult(agent:Agent,prompt:string,skill:string){
 const language=agent.language==='Bahasa Indonesia';
 const intro=language?'CONTOH ALUR — bukan hasil riset atau jawaban AI.':'WORKFLOW SAMPLE — not AI-generated or researched results.';
 const steps:Record<string,string>={research:language?'1. Perjelas pertanyaan dan ruang lingkup.\n2. Cari sumber primer dan periksa tanggalnya.\n3. Bandingkan temuan dan tautkan sumber.\n4. Tandai informasi yang belum bisa diverifikasi.':'1. Clarify the question and its scope.\n2. Retrieve primary sources and check their dates.\n3. Compare findings and attach source links.\n4. Flag anything that cannot be verified.',write:language?'1. Tentukan pembaca, tujuan, dan format.\n2. Susun kerangka berdasarkan brief.\n3. Buat draf dengan gaya yang dipilih.\n4. Minta persetujuan sebelum publikasi.':'1. Identify the audience, purpose, and format.\n2. Outline the supplied brief.\n3. Draft in the selected tone.\n4. Ask for review before publishing.',document:language?'1. Baca teks yang disediakan.\n2. Temukan poin utama dan kutipan pendukung.\n3. Susun tindakan dan pertanyaan terbuka.\n4. Jangan menambahkan fakta di luar dokumen.':'1. Read the supplied text.\n2. Extract key points with supporting passages.\n3. List action items and open questions.\n4. Avoid claims beyond the document.',
 summarize:language?'1. Baca seluruh teks.\n2. Tulis TL;DR satu kalimat.\n3. Daftar poin utama.\n4. Ambil tindakan beserta pemiliknya bila disebutkan.':'1. Read the whole text.\n2. Write a one-line TL;DR.\n3. List the key points.\n4. Pull out action items with owners when stated.',
 translate:language?'1. Kenali bahasa sumber dan gaya.\n2. Terjemahkan dengan mempertahankan nama dan format.\n3. Tandai frasa tanpa padanan langsung.':'1. Detect the source language and tone.\n2. Translate while keeping names and formatting.\n3. Flag phrases without a direct equivalent.',
 brainstorm:language?'1. Perjelas masalahnya.\n2. Hasilkan ide yang berbeda-beda.\n3. Urutkan berdasarkan dampak dan usaha.':'1. Clarify the problem.\n2. Generate distinct ideas.\n3. Rank them by impact and effort.',
 code:language?'1. Baca kode dan tujuannya.\n2. Jelaskan alurnya langkah demi langkah.\n3. Catat bug dan kasus tepi.':'1. Read the code and its purpose.\n2. Explain the flow step by step.\n3. Note bugs and edge cases.',
 monitor:language?'1. Temukan alamat di tugas (atau pakai wallet yang ditautkan).\n2. Baca saldonya di blok terbaru.\n3. Bandingkan dengan pemeriksaan sebelumnya dan daftar transfer RHIO.\n4. Laporkan yang berubah, tanpa mengarang angka.':'1. Find the address in the task (or use your linked wallet).\n2. Read its balances at the latest block.\n3. Compare with the last check and list RHIO transfers.\n4. Report what changed, never inventing a number.',
 whales:language?'1. Ambil catatan token RHIO dari server.\n2. Lihat transfer terbesar 24 jam terakhir dan holder baru.\n3. Bandingkan dengan holder terbesar dan suplai.\n4. Laporkan yang bergerak, tanpa menebak pemilik atau harga.':'1. Take the server\'s record of the RHIO token.\n2. Look at the biggest transfers of the last 24 hours and the new holders.\n3. Set them against the biggest holders and the supply.\n4. Report what moved, never guessing an owner or a price.',
 chat:language?'1. Baca pesan dan percakapan sebelumnya.\n2. Jawab singkat dengan gaya karakter agent.\n3. Tanyakan balik bila ada yang belum jelas.':'1. Read the message and the conversation so far.\n2. Answer briefly in the agent\u2019s own voice.\n3. Ask back when something is unclear.',
 planner:language?'1. Pecah tujuan menjadi langkah.\n2. Urutkan dan beri estimasi waktu.\n3. Tandai risiko dan ketergantungan.':'1. Break the goal into steps.\n2. Order them and estimate time.\n3. Flag risks and dependencies.'};
 return `${intro}\n\n${language?'Tugas':'Your task'}: ${prompt}\n\n${language?'Rencana agent':'Agent plan'}\n${steps[skill]||steps.research}\n\n${language?'Hubungkan layanan AI untuk menjalankan pekerjaan ini. Tidak ada penelusuran web atau tindakan eksternal yang dilakukan.':'Connect an AI service to execute this work. No web search or external action has been performed.'}`;
}
